services:
  db_processor:
    build:
      context: .
      dockerfile: Dockerfile
    image: telemetry_processors
    container_name: lap_timer_processor
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
      IN_DOCKER: 1
      HOST_IP: 'host.docker.internal'
    volumes:
      - ../../ingest/mqtt_handler.py:/processors/mqtt_handler.py
      - ../../../analysis/sql_utils/db_handler.py:/processors/db_handler.py
      - ../../../analysis/sql_utils/DB_description.pkl:/DB_description.pkl
    networks:
      - telemetry_network

networks:
  telemetry_network:
    external: true