version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    volumes:
      - telemetry_db:/var/lib/postgresql/data
      - ./db_init_v1.0.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: electric
      POSTGRES_PASSWORD: 2fast2quick
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_storage:/var/lib/grafana
    ports:
      - "3000:3000"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: unless-stopped
    depends_on:
      - mosquitto
      - grafana
      - db
    volumes:
      - type: bind
        source: ./telegraf_conf_gen
        target: /LHR/telegraf_conf_gen
    entrypoint: bash "/LHR/telegraf_conf_gen/run.sh"

volumes:
  grafana_storage:
    external: true
  telemetry_db:
    external: true
