version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"

  python_client:
    image: telemetry_backend
    container_name: python_client
    environment:
      PYTHONUNBUFFERED: 1
      IN_DOCKER: 1
    depends_on:
      - mosquitto
    volumes:
      - ../analysis/sql_utils/db_handler.py:/ingest/db_handler.py
      - ../analysis/sql_utils/DB_description.pkl:/ingest/DB_description.pkl

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    volumes:
      - telemetry_db:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: electric
      POSTGRES_PASSWORD: 2fast2quick
    ports:
      - "5432:5432"
    tmpfs:
      - /tmp
      - /run/postgresql

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_storage:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  grafana_storage:
    external: true
  telemetry_db:
    external: true
