<<<<<<< HEAD
user=("mwiesenfeld" "lbryson" "kyu" "kjohnston" "rpuppala" "lhong" "acloran" "rhanks" "cdwyer" "cwu" "jbardales" "aakkineni" "jzeng" "gbhaskar" "anargund" "ptorres" "mbarsotti" "cpayne" "rmata" "apandit" "rprabhu" "ajensen" "sagnihotri" "pbangaru" "rhorvath" "tyan" "ksinghvi" "moddiraju" "averma" "ssyed" "bbartley" "hstus" "ksloan" "dlu" "mmekha" "asuresh" "cpsaropoulos" "rkirk" "sshah" "ppopoviciu" "ymittal" "abalamehta" "ppatki" "anederveld" "pyedavelli" "parya" "povezov" "bcalixto" "tkasson" "awhite" "kchandra" "ajia" "asimmons" "bhuff" "vramachandran" "jhaase" "jmoreno" "kjohnston" "dhammerbeck" "ydundar" "dsaballos" "spatil" "lballengee" "esegura" "npai" "sjoshi" "vrajgopal" "ccastillo" "vgarcia" "kdavid" "amelachuri" "dgupta" "hdgama" "asaggar" "mlahti" "ksingh" "yabdulkader" "cosgood" "ayande " "lkatta" "zjafri" "tkholay" "kpham" "dnederveld " "jcarrillo" "arathnakumar" "aosullivan" "tkothapalle" "ddubinsky" "ydundar" "vbhalla" "pnittala" "cnelson" "amiller" "vshetty" "rwang" "mchowdhury" "adiaz" "wschmitt" "amomin" "abulusu" "crude" "elo" "moviedo" "rpatkar" "skoebele" "vburla" "rnaniwadekar" "rsong" "jchacko" "cmoore" "cosgood" "rpalanikumar")
pass=("n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre")
=======
user=("mwiesenfeld" "lbryson" "kyu" "kjohnston" "rpuppala" "lhong" "acloran" "rhanks" "cdwyer" "cwu" "jbardales" "aakkineni" "jzeng" "gbhaskar" "anargund" "ptorres" "mbarsotti" "cpayne" "rmata" "apandit" "rprabhu" "ajensen" "sagnihotri" "pbangaru" "rhorvath" "tyan" "ksinghvi" "moddiraju" "averma" "ssyed" "bbartley" "hstus" "ksloan" "dlu" "mmekha" "asuresh" "cpsaropoulos" "rkirk" "sshah" "ppopoviciu" "ymittal" "abalamehta" "ppatki" "anederveld" "pyedavelli" "parya" "rovezov" "bcalixto" "tkasson" "awhite" "kchandra" "ajia" "asimmons" "bhuff" "vramachandran" "jhaase" "jmoreno" "kjohnston" "dhammerbeck" "ydundar" "dsaballos" "spatil" "lballengee" "esegura" "npai" "sjoshi" "vrajgopal" "ccastillo" "vgarcia" "kdavid" "amelachuri" "dgupta" "hdgama" "asaggar" "mlahti" "ksingh" "yabdulkader" "cosgood" "ayande " "lkatta" "zjafri" "tkholay" "kpham" "dnederveld " "jcarrillo" "arathnakumar" "aosullivan" "tkothapalle" "ddubinsky" "ydundar" "vbhalla" "pnittala" "cnelson" "amiller" "vshetty" "rwang" "mchowdhury" "adiaz" "wschmitt" "amomin" "abulusu" "crude" "elo" "moviedo" "rpatkar" "skoebele" "vburla" "rnaniwadekar" "rsong" "jchacko" "cmoore" "cosgood" "rpalanikumar" "jwang" "ahuang" "tmiranda" "ajaimurugesh")
pass=("n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "n00tn00t" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre" "lhre")
>>>>>>> origin/main

for i in ${!user[@]}; do
    htpasswd -b /etc/svnusers.htpasswd ${user[$i]} ${pass[$i]}
done