admin=("mwiesenfeld" "lbryson" "kyu" "kjohnston" "rpuppala" "lhong" "acloran" "rhanks" "cdwyer")
user=("cwu" "jbardales" "aakkineni" "jzeng" "gbhaskar" "anargund" "ptorres" "mbarsotti" "cpayne" "rmata" "apandit" "rprabhu" "ajensen" "sagnihotri" "pbangaru" "rhorvath" "tyan" "ksinghvi" "moddiraju" "averma" "ssyed" "bbartley" "hstus" "ksloan" "dlu" "mmekha" "asuresh" "cpsaropoulos" "rkirk" "sshah" "ppopoviciu" "ymittal" "abalamehta" "ppatki" "anederveld" "pyedavelli" "parya" "rovezov" "bcalixto" "tkasson" "awhite" "kchandra" "ajia" "asimmons" "bhuff" "vramachandran" "jhaase" "jmoreno" "kjohnston" "dhammerbeck" "ydundar" "dsaballos" "spatil" "lballengee" "esegura" "npai" "sjoshi" "vrajgopal" "ccastillo" "vgarcia" "kdavid" "amelachuri" "dgupta" "hdgama" "asaggar" "mlahti" "ksingh" "yabdulkader" "cosgood" "ayande " "lkatta" "zjafri" "tkholay" "kpham" "dnederveld " "jcarrillo" "arathnakumar" "aosullivan" "tkothapalle" "ddubinsky" "ydundar" "vbhalla" "pnittala" "cnelson" "amiller" "vshetty" "rwang" "mchowdhury" "adiaz" "wschmitt" "amomin" "abulusu" "crude" "elo" "moviedo" "rpatkar" "skoebele" "vburla" "rnaniwadekar" "rsong" "jchacko" "cmoore" "cosgood" "rpalanikumar" "jwang" "ahuang" "tmiranda" "ajaimurugesh" "bakinicioglu" "aparuthi" "cmedina" "sdai" "pjoshi" "asharma" "atruong" "agrobmyer" "tfazio" "jrisberg" "tbooth" "svatts" "apolamuri" "gramanarayanan" "tdumas" "ashetty" "htudor" "hseenivasan" "mzhong" "sli" "adimauro" "kchang" "akuppahally" "mzhong" "szapata" "gmarshall" "uramesh" "avasa" "hwilliams" "lcarr" "ajain" "akanaparthi" "achintalapally" "abarnhart" "nyee" "mnardi" "abatra" "kchennupati" "eliu")

for i in ${!admin[@]}; do
    htpasswd -b /etc/svnusers.htpasswd ${admin[$i]} "n00tn00t"
done

for i in ${!user[@]}; do
    htpasswd -b /etc/svnusers.htpasswd ${user[$i]} "lhre"
done