version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    volumes:
      - telemetry_db:/var/lib/postgresql/data
      - ./db_init_test.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: electric
      POSTGRES_PASSWORD: 2fast2quick
    ports:
      - "5432:5432"

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: unless-stopped
    depends_on:
      - mosquitto
      - db
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

volumes:
  telemetry_db:
    external: true

